kind: wasmer.io/App.v0
name: lazismu-pcm-kasihan
owner: yuumuu
package: .

debug: false

redirect:
  force_https: true

env:
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: "base64:HWN7k/1ZHqFFY1KPiTzMlovydt+Nil71I8nzsLiHx+w="
  APP_URL: "https://lazismu-pcm-kasihan.wasmer.app"
  APP_MAINTENANCE_DRIVER: file
  SESSION_DRIVER: database
  QUEUE_CONNECTION: sync
  CACHE_STORE: database
  FILESYSTEM_DISK: local
  LOG_CHANNEL: stderr
  LOG_LEVEL: error

capabilities:
  database:
    engine: mysql

locality:
  regions:
    - us-socal1

scaling:
  mode: single_concurrency

health_checks:
  - http:
      method: get
      path: /
      interval: 30s
      timeout: 10s
      unhealthy_threshold: 3
      healthy_threshold: 1
      expected_status_codes:
        - 200
        - 302
        - 301
