[dependencies]
"php/php" = "=8.3.4"

[fs]
"/app/" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = [
    "-t", "/app/public",
    "-S", "0.0.0.0:8080",
    "/app/public/index.php"
]
